### ISSUE TITLE
API Design - Create an OpenAPI Specification-based Contract link has broken.

### ISSUE THREAD

**Issue by danieloh30** [hguerrero/3scale-api-workshop#13]
In Optional Labs section, the following bold link[1] has broken.
We recommend you to begin your journey with the first lab **API Design - Create an OpenAPI Specification-based Contract**
[1]https://github.com/hguerrero/3scale-api-workshop/blob/master/docs/labs/lab01.md

**Comment by hguerrero** [comment]
solved with #16
