### ISSUE TITLE
Error when provisioning 3scale during installation

### ISSUE THREAD

**Issue by dsoffner** [hguerrero/3scale-api-workshop#25]
Hugo,

I am getting the following error when running the Ansible scripts to install the labs on RHPDS during provisioning the 3scale environment:

`TASK [provision_threescale : Get id for client 'www-secured'] ***********************************************************************************************************************
ok: [localhost]

TASK [provision_threescale : set_fact] **********************************************************************************************************************************************
ok: [localhost]

TASK [provision_threescale : debug] *************************************************************************************************************************************************
ok: [localhost] => {
    "IdClientApp": ""
}

TASK [provision_threescale : Update the rh sso app] *********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content": "", "content_length": "0", "date": "Wed, 15 Aug 2018 11:16:57 GMT", "failed": true, "msg": "Status code was not [204]: HTTP Error 405: Method Not Allowed", "redirected": false, "status": 405, "url": "https://secure-sso-rh-sso.apps.auslab30.openshiftworkshop.com/auth/admin/realms/threescale/clients/"}
	to retry, use: --limit @/home/ec2-user/3scale-api-workshop/support/install/ansible/playbooks/openshift/install.retry`

**Comment by hguerrero** [comment]
solved with d1c39efe296d03fa3275889bbe17b7021e905aaa
